CREATE TABLE AUDIO_FILE (File_Name text, AF_Link varchar (2048), Transcript_Link varchar (2048), Date_Originated int CHECK ((Date_Originated > 1800) AND (Date_Originated < 2050)), View_Count int DEFAULT '0', Like_Count int DEFAULT '0', PRIMARY KEY (File_Name));

CREATE TABLE TAG (Tag_Name varchar (15) PRIMARY KEY);

CREATE TABLE USERS (User_ID int  CHECK ((User_ID > 99999) AND (User_ID < 1000000)) PRIMARY KEY, Password varchar (255), User_Type varchar (9) CHECK (User_type in ('Admin', 'Moderator', 'Guest') ) DEFAULT 'Guest', User_Creator_ID int DEFAULT '100000', FOREIGN KEY (User_Creator_ID) REFERENCES USERS (User_ID) ON DELETE SET DEFAULT ON UPDATE CASCADE);

CREATE TABLE COMMENT (Comment_ID SERIAL PRIMARY KEY, User_Comment varchar (280) NOT NULL, Date_Created DATE, User_ID int, File_Name text, FOREIGN KEY (User_ID) REFERENCES USERS (User_ID) ON DELETE SET NULL ON UPDATE CASCADE, FOREIGN KEY (File_Name) REFERENCES AUDIO_FILE (File_Name) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE DEFINES_CHARACTERISTIC_OF (File_Name text, Tag_Name varchar (15), FOREIGN KEY (Tag_Name) REFERENCES TAG(Tag_Name) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (File_Name) REFERENCES AUDIO_FILE (File_Name) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE CAN_SUGGEST_EDITS (Suggestion_ID SERIAL PRIMARY KEY, File_Name text, User_ID int, Suggestion varchar (280), FOREIGN KEY (User_ID) REFERENCES USERS (User_ID) ON DELETE SET NULL ON UPDATE CASCADE, FOREIGN KEY (File_Name) REFERENCES AUDIO_FILE (File_Name) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE VIEW Audio_File_Tags AS SELECT * FROM AUDIO_FILE AS AF NATURAL JOIN DEFINES_CHARACTERISTIC_OF AS DC WHERE AF.File_Name = DC.File_Name;

CREATE VIEW User_Comments AS SELECT * FROM USERS AS U NATURAL JOIN COMMENT AS C WHERE U.User_ID = C.User_ID;

CREATE VIEW Audio_File_Comments AS SELECT * FROM AUDIO_FILE AS AF NATURAL JOIN COMMENT AS C WHERE AF.File_Name = C.File_Name;

CREATE VIEW Suggest_File_Edit AS SELECT * FROM AUDIO_FILE AS AF NATURAL JOIN CAN_SUGGEST_EDITS AS CSE WHERE AF.File_Name = CSE.File_Name;

CREATE VIEW Creator AS SELECT U.User_ID, U.User_Type, U2.USER_ID AS CREATOR_id, U2.User_Type AS CREATOR_TYPE FROM USERS AS U JOIN USERS AS U2 ON U.User_Creator_ID = U2.User_ID;
